site_name: Sandpyper

site_url: https://npucino.github.io/sandpyper/

repo_url: https://github.com//npucino//sandpyper

use_directory_urls: false


theme:
    palette:
        scheme: preference
    name: "material"
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        - navigation.expand
        #- navigation.tabs
    custom_dir: "docs/overrides"


plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True
        execute: False

markdown_extensions:
    - admonition
    - codehilite
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - pymdownx.arithmatex:
        generic: true
    - toc:
          permalink: true

extra_javascript:
  - javascripts/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js




# google_analytics:
#     - UA-XXXXXXXXX-X
#     - auto

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Report Issues: https://github.com//npucino//sandpyper//issues
    - Methods:
        - Introduction: Introduction.md
        - Elevation analysis: extraction and lod.md
        - Data cleaning: ML and SA.md
        - Hotspot analysis: hotspot_methods.md
        - BCDs: bcds_method.md
        - Volumetrics: volumetrics_method.md
    - API Reference:
      - sandpyper module: sandpyper.md
      - common module: common.md
    - Notebooks:
        - notebooks/1 - Introduction and data preparation.ipynb
        - notebooks/2 - Profiles extraction, unsupervised sand labelling and cleaning.ipynb
        - notebooks/3 - Profile dynamics.ipynb
        - notebooks/Space analysis - teaser.ipynb
