site_name: Sandpyper

site_url: https://npucino.github.io/sandpyper/

repo_url: https://github.com//npucino//sandpyper

theme:
    palette:
        scheme: preference
    name: "material"
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        - navigation.expand
        #- navigation.tabs
    custom_dir: "docs/overrides"


plugins:


    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True
        execute: False


markdown_extensions:
    - admonition
    - codehilite
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# google_analytics:
#     - UA-XXXXXXXXX-X
#     - auto

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Report Issues: https://github.com//npucino//sandpyper//issues
    - API Reference:
      - hotspot module: hotspot.md
      - outils module: outils.md
      - volumetrics module: volumetrics.md
      - profile module: profile.md
      - labels module: labels.md
      - dynamics module: dynamics.md
      - space module: space.md
    - Notebooks:
        - notebooks/Profile_Extraction.ipynb
        - notebooks/Sand_KMeans_labeling.ipynb
        - notebooks/Sand_No_Sand_classification_beachface.ipynb


    #- Notebooks:
        #- notebooks//Profile_Extraction.ipynb
        #- notebooks//Sand_KMeans_labeling.ipynb
        #- notebooks//Sand_No_Sand_classification_beachface.ipynb
