on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: true
            matrix:
                config:
                    - { os: windows-latest, py: "3.7.9" }
                    # - { os: macOS-latest, py: "3.7.9" }
                    #- { os: ubuntu-latest, py: "3.6" }
                    #- { os: ubuntu-latest, py: "3.7.9" }

        env:
            SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        steps:
            - name: CHECKOUT CODE
              uses: actions/checkout@v2
            - name: SETUP PYTHON
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.config.py }}
            
            - name: SETUP CONDA
            - uses: s-weigand/setup-conda@v1
            - run: conda --version

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  # pip install --user --no-cache-dir Cython
                  conda install -c conda-forge gdal==3.1.4
                  pip install richdem
                  # pip install --user -r requirements_dev.txt
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
