on:
    push:
        branches:
            - master
            - v1
    pull_request:
        branches:
            - master
            - v1

name: build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: windows-latest, py: "3.8" }
                    - { os: macOS-latest, py: "3.8" }
                    - { os: ubuntu-latest, py: "3.8" }
                    - { os: ubuntu-latest, py: "3.9" }
        env:
            SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

        steps:
            - name: CHECKOUT CODE
              uses: actions/checkout@v2
            - name: SETUP PYTHON
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.config.py }}

            - name: SETUP CONDA
              uses: s-weigand/setup-conda@v1

            - name: Install dependencies
              run: |
                  pip install --user --no-cache-dir Cython
                  python -m pip install --upgrade pip
                  conda config --add channels conda-forge
                  conda config --set channel_priority strict
                  conda install --file requirements.txt
                  conda install --file requirements_dev.txt
                  conda install -c conda-forge ipywidgets

            - name: PKG-TEST
              run: |
                  python -m unittest discover
