name: docs
on:
    push:
        branches:
            - master
            - v1
jobs:
    deploy:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - uses: s-weigand/setup-conda@v1

              with:
                  python-version: 3.7.9
            - name: Install dependencies
              run: |
                  conda config --add channels conda-forge
                  conda config --set channel_priority strict
                  conda install --file requirements.txt
            #- name: PKG-TEST
            #  run: |
                #  python -m unittest discover tests/
            - run: pip install mkdocs==1.1.2 mkdocs-material mkdocstrings mkdocs-git-revision-date-plugin mkdocs-jupyter livereload python-markdown-math

            - run: mkdocs gh-deploy --force
